A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns= [
    path('detail/', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='add'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path('create/', views.order_create, name='create'),
    path('order_detail/', views.order_detai, name='order-detail'),
    path('order_paid/', views.order_paid, name='paid'),
    path('order_delete/<int:id>/', views.order_delete, name='delete'),
    #path('payment/<int;order_id>/<price>/', ....),
    #path('verify/', ....),
    path('apply/<int:order_id>/', views.coupon, name='coupon'),
]

shop/urls.py
from django.urls import path
from .views import index,detail

app_name = 'shop'

urlpatterns = [
    path('', index, name='index'),
    path('detail/<slug>/', detail, name='detail')
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
# Create your models here.
from django.conf import settings
from shop.models import Products
from django.core.validators import MinValueValidator, MaxValueValidator


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='order')
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    discount = models.IntegerField(blank=True, null=True, default=None)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.user}-{str(self.id)}'

    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        if self.discount:
            discount_price = (self.discount / 100) * total
            return int(total - discount_price)
        else:
            return total

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Products, on_delete=models.CASCADE,related_name='order_items')
    price = models.IntegerField()
    quantity = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity


    
class Coupon(models.Model):
    code = models.CharField(max_length=30, unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    active = models.BooleanField(default=False)

    def __str__(self):
        return self.code

shop/models.py
from django.db import models
from uuid import uuid4
# Create your models here.


class Products(models.Model):
    price = models.IntegerField()
    image = models.ImageField(upload_to='media/')
    title = models.CharField(max_length=200)
    slug = models.SlugField(default=uuid4, unique=True, editable=False) 
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.title

cart/forms.py
from django import forms



class CartAddForm(forms.Form): 
    # برای ارسال تعداد(مقادیر) خرید یک محصول به درون سبد این فرم درون اپ مربوط به نمایش محصول قرار میگیرد
    quantity = forms.IntegerField(
        min_value=1, 
        max_value=9, 
    )

orders/forms.py
from django import forms


class CouponForm(forms.Form):
    code = forms.CharField(label='Coupon')

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from .cart import Cart
from shop.models import Products
from .forms import CartAddForm
from django.views.decorators.http import require_POST



def detail(request): #نمایش جزییات سبد خرید کاربر
    cart = Cart(request)
    # مقذار سلف.سشن رو , که حاوی سشن کاربر بخش های مربوط به کارت خرید رو به ما برمیگردونه
    context = {
        'cart':cart,
    }


    return render(request, 'cart/detail.html', {'cart':cart})


@require_POST
def cart_add(request, product_id): 
    # اضافه کردن یک محصول به سبد خرید(این ویو وظیفه ارسال اطلاعات به فایل کارت برای ذخیره در سشن)
    cart = Cart(request)
    prd = get_object_or_404(Products, pk=product_id)
    form = CartAddForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=prd, quantity=cd['quantity'])
    return redirect('cart:detail')


def cart_remove(request, product_id):
    #در این ویو اقدام به حذف یک محصول از داخل کارت رو انجام میدیم
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.remove(product)
    return redirect('cart:detail')

orders/views.py
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404

# Create your views here.
from django.contrib.auth.decorators import login_required
from .models import Order, OrderItem, Coupon
from cart.cart import Cart
from .forms import CouponForm
from django.utils import timezone
from django.views.decorators.http import require_POST



@login_required
def order_create(request):
    cart=Cart(request)
    if cart.get_total_price() != 0:
        order = Order.objects.create(user=request.user)
        for item in cart:
            OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
        cart.clear()
        return redirect('orders:order-detail')
    return redirect('shop:index')



@login_required
def order_delete(request, id):
    order = get_object_or_404(Order, id=id)

    if order.user == request.user and order.paid == False:
        order.delete()
        return redirect('orders:order-detail')
    return redirect('orders:order-detail')


@login_required
def order_detai(request):
    orders = Order.objects.filter(user = request.user, paid=False)

    context = {
        'orders':orders,
        'form':CouponForm
    }
    return render(request, 'orders/orders_detail.html', context)


@login_required
def order_paid(request):
    orders = Order.objects.filter(user = request.user, paid=True)

    context = {
        'orders':orders,
    }
    return render(request, 'orders/orders_paid.html', context)

@require_POST
def coupon(request, order_id):
    now = timezone.now()
    form = CouponForm(request.POST)
    if form.is_valid():
        code = form.cleaned_data['code']
        try:
            coupon = Coupon.objects.get(code__iexact=code, valid_from__lte=now, valid_to__gte=now, active=True)

        except Coupon.DoesNotExist:
            messages.error(request, 'this coupon not exsits', 'danger')
            return redirect('orders:detail')
        order = Order.objects.get(id=order_id)
        order.discount = coupon.discount
        order.save()
    return redirect('orders:detail')

shop/views.py
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.generic import ListView
from .models import Products
from cart.forms import CartAddForm


def index(request):
    pro = Products.objects.all()
    context = {
        'products':pro,
    }

    return render(request, 'shop/index.html', context)



def detail(request, slug):
    product = get_object_or_404(Products, slug=slug)

    context = {
        'prd':product,
        'form':CartAddForm
    }

    return render(request, 'shop/detail.html', context)

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% block body %}

<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">product</th>
        <th scope="col">quantity</th>
        <th scope="col">unit price</th>
        <th scope="col">total price</th>
        <th scope="col">delete</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}  
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ item.product }}</td>
          <td>{{ item.quantity }}</td>
          <td>{{ item.price }}</td>
          <td>{{ item.total_price}}</td>
          <td><a href="{% url 'cart:remove' item.product.id %}">remove</a></td>
        </tr>
      {% endfor %}
      <tr>
          <td>total All</td>
          <td colspan="3"></td>
          <td>{{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>    
  
  <a href="{% url 'orders:create' %}" class="btn btn-primary">checkout</a>

  {% endblock %}

orders/templates/orders/order.html
{% extends 'base.html' %}

{% block body %}
    {{ order.get_total_price }}
{% endblock %}

orders/templates/orders/orders_detail.html
{% extends 'base.html' %}

{% block body %}
{% for order in orders %}

<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col"> #</th>
        <th scope="col"> image</th>
        <th scope="col"> price</th>
        <th scope="col"> quantity </th>
        <th scope="col"> total</th>
        <th scope="col"> link </th>
      </tr>
    </thead>
    <tbody>
            {%for ord in order.items.all %}
            <tr>

                <td scope="row">{{ forloop.counter }}</td>
                <td><img src="{{ord.product.image.url}} " style="width: 150px; height: 150px;" alt=""> </td>
                <td> {{ord.price}} </td>
                <td> {{ord.quantity}} </td>
                <td> {{ord.get_cost}} </td>
                <td> <a href="{% url 'shop:detail' ord.product.slug %}"> {{ord.product.slug}} </a> </td>
            </tr>

            {% endfor %}
       
        <tr>
            <td>
                <small>total pay:</small>
            </td>
            <td colspan="3"></td>
            <td>
                <strong>{{order.get_total_price}}</strong>
            </td>
            <td><span>
                <form action="{% url 'orders:coupon' order.id%}" method="POST">
                    {% for field in form %} {{field}}{% endfor %}
                    <input type="submit" class="btn-success" value="coupon">
                </form>
            </span></td> 

        </tr>
        <tr>
            <td>
                <a href="" class="btn btn-primary">Pay</a>
            </td>
            <td>
                <a href="{% url 'orders:delete' order.id%}" class="btn btn-danger">delete</a>                
            </td>
            <td colspan="3"></td>
            <td>
               <strong>date:</strong> <small>{{ order.created|date }}</small>
            </td>
        </tr>
    </tbody> 
</table> 
{% endfor %}
{% endblock %}

orders/templates/orders/orders_paid.html
{% extends 'base.html' %}

{% block body %}
{% for order in orders %}

<table class="table table-dark">
    <thead>
        <tr>
            <td>name: {{ request.user.first_name }} {{request.user.last_name}}</td>
        </tr>
        <tr>
            <td colspan="4"></td>
            <td><strong>date: </strong> <small>{{ order.created|date }}</small></td>
        </tr>
      <tr>
        <th scope="col">#</th>
        <th scope="col">image</th>
        <th scope="col">unit price</th>
        <th scope="col"> quantity </th>
        <th scope="col"> total price </th>
      </tr>
    </thead>
    <tbody>
            {%for ord in order.items.all %}
            <tr>
                <td scope="row">{{ forloop.counter }}</td>
                <td> {{ ord.product }}</td>
                <td> {{ord.price}} </td>
                <td> {{ord.quantity}} </td>
                <td> {{ ord.get_cost }}</td>
            </tr>

            {% endfor %}
        <tr>
            <td><small>total pay:</small></td>
            <td colspan="3"></td>
            <td><strong>{{order.get_total_price}}</strong> </td>
        </tr>
        <tr>
            <td><a href="" class="btn btn-success">factor</a></td>
        </tr>
{% endfor %}
</tbody> 
</table> 
{% endblock %}

shop/templates/shop/detail.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <h1>Hi Cart</h1>
        <img src="{{ prd.image.url }}" style="height: 150px; width: 150px;" alt=""> <br>
        <small>name:</small> <strong> {{prd.name}} </strong> <br>
        <small>slug:</small> <strong> {{prd.slug}} </strong> <br>
        <small>title:</small> <strong> {{prd.title}} </strong> <br>
        <small>price:</small> <strong> {{prd.price}} </strong><small>ریال</small> <br>
        <h3>
        <form action="{% url 'cart:add' prd.id %}" method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="add to cart">
        </form>
        </h3>

        <hr>
{% endblock %}

shop/templates/shop/index.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

    <h1>Hi Cart</h1>
    {% for prd in products %}
        <img src="{{ prd.image.url }}" style="height: 150px; width: 150px;" alt=""> <br>
        <small>name:</small> <strong> {{prd.name}} </strong> <br>
        <a href="{% url 'shop:detail' prd.slug %}"><small>slug:</small> <strong> {{prd.slug}} </strong></a> <br>
        <hr>
    {% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    {% include 'inc/nav.html' %}
    <div class="jumbotron">
    {% include 'inc/message.html' %}

    {% block body %}   {% include 'inc/messages.html' %}    {% endblock %}
    
    </div>

    {% include 'nav/foot.html' %}
  </body>
</html>

templates/inc/foot.html
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crosso></script>

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/nav.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'shop:index' %}">Home </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:detail' %}">Basket Buy</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'orders:order-detail' %}">Order</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'orders:paid' %}">Factor</a>
        </li>
    </ul>
</nav>